# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy

gomod:
  proxy: true

builds:
  - env: ["CGO_ENABLED=0"]
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags: ["-trimpath"]
    targets: ["go_first_class"]
    id: 'commit'
    binary: commit
    main: ./cmd/commit
  - env: ["CGO_ENABLED=0"]
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags: ["-trimpath"]
    targets: ["go_first_class"]
    id: 'checkout'
    binary: checkout
    main: ./cmd/checkout

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999

brews:
  - name: checkout
    description: JSON Log Viewer tool.
    license: MIT
    homepage: https://github.com/mrados7/homebrews
    tap:
      owner: mrados7
      name: homebrew-main
    test: system "#{bin}/checkout", "-help"
    install: |-
      bin.install "checkout"

release:
  footer: |

    ---

    _Released with [GoReleaser](https://goreleaser.com)!_
