# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy

gomod:
  proxy: true

builds:
  - env: ["CGO_ENABLED=0"]
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags: ["-trimpath"]
    targets: ["go_first_class"]
    id: 'commit'
    binary: commit
    main: ./cmd/commit
  - env: ["CGO_ENABLED=0"]
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags: ["-trimpath"]
    targets: ["go_first_class"]
    id: 'checkout'
    binary: checkout
    main: ./cmd/checkout

archives:
  - id: commit
    builds:
      - commit
  - id: checkout
    builds:
      - checkout

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999

brews:
  - name: checkout
    ids:
    - checkout
    description: Checkout is a tool for checking out new git branch with naming convention
    license: MIT
    homepage: https://github.com/mrados7/homebrews
    dependencies:
      - git
    repository:
      owner: mrados7
      name: homebrews
      branch: main
    test: system "#{bin}/checkout", "-help"
    install: |-
      bin.install "checkout"

  - name: commit
    ids:
    - commit
    description: Commit is a tool for commiting changes with naming convention
    license: MIT
    homepage: https://github.com/mrados7/homebrews
    dependencies:
      - git
    repository:
      owner: mrados7
      name: homebrews
      branch: main
    test: system "#{bin}/commit", "-help"
    install: |-
      bin.install "commit"
      

release:
  footer: |

    ---

    _Released with [GoReleaser](https://goreleaser.com)!_
